### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by jcserracampos** [jcserracampos/100diasdecodigo_bot#3]
First I need to know what I want to test.
The bot has two functions, one to test if a tweet is a retweet and another to retweet.

After I should use Jest to create my tests.

**Comment by alexanmtz** [comment]
@jcserracampos check it here about tests on Jest: [https://alexandremagno.net/2018/09/testando-componentes-react-jest/](https://alexandremagno.net/2018/09/testando-componentes-react-jest/)

This is a good reference for front-end tests

**Comment by alexanmtz** [comment]
Great @WarleyFranco ! Should we close this @jcserracampos ?
